/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BaseBreadcrumb: typeof import('./components/shared/BaseBreadcrumb.vue')['default']
    CardHeader: typeof import('./components/shared/CardHeader.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiChildCard: typeof import('./components/shared/UiChildCard.vue')['default']
    UiParentCard: typeof import('./components/shared/UiParentCard.vue')['default']
  }
}
