/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BaseBreadcrumb: typeof import('./components/shared/BaseBreadcrumb.vue')['default']
    BooleanIcon: typeof import('./components/shared/BooleanIcon.vue')['default']
    BoolSelectInput: typeof import('./components/app/BoolSelectInput.vue')['default']
    CardHeader: typeof import('./components/shared/CardHeader.vue')['default']
    ConfigEditor: typeof import('./components/app/ConfigEditor.vue')['default']
    CopyIcon: typeof import('./components/shared/CopyIcon.vue')['default']
    DashboardCard: typeof import('./components/shared/DashboardCard.vue')['default']
    DateRangeSelectInput: typeof import('./components/app/DateRangeSelectInput.vue')['default']
    EpochField: typeof import('./components/app/EpochField.vue')['default']
    HostPortSelectInput: typeof import('./components/app/HostPortSelectInput.vue')['default']
    InfoDialog: typeof import('./components/shared/InfoDialog.vue')['default']
    JsonViewer: typeof import('./components/shared/JsonViewer.vue')['default']
    MachineSelectInput: typeof import('./components/app/MachineSelectInput.vue')['default']
    MinerSelectInput: typeof import('./components/app/MinerSelectInput.vue')['default']
    PriceInput: typeof import('./components/app/PriceInput.vue')['default']
    PrometheusChart: typeof import('./components/app/PrometheusChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusIcon: typeof import('./components/shared/StatusIcon.vue')['default']
    StoragePathTable: typeof import('./components/app/StoragePathTable.vue')['default']
    TableFilterMenu: typeof import('./components/app/TableFilterMenu.vue')['default']
    TaskDetailsDialog: typeof import('./components/app/TaskDetailsDialog.vue')['default']
    TaskNameSelectInput: typeof import('./components/app/TaskNameSelectInput.vue')['default']
    TruncatedChip: typeof import('./components/shared/TruncatedChip.vue')['default']
    TruncatedText: typeof import('./components/shared/TruncatedText.vue')['default']
    UiChildCard: typeof import('./components/shared/UiChildCard.vue')['default']
    UiParentCard: typeof import('./components/shared/UiParentCard.vue')['default']
    UiTableCard: typeof import('./components/shared/UiTableCard.vue')['default']
    UiTitleCard: typeof import('./components/shared/UiTitleCard.vue')['default']
    UiWidgetCard: typeof import('./components/shared/UiWidgetCard.vue')['default']
  }
}
