package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/strahe/curio-dashboard/graph"
	"github.com/strahe/curio-dashboard/graph/model"
)

// UsedBy is the resolver for the usedBy field.
func (r *configResolver) UsedBy(ctx context.Context, obj *model.Config) ([]*model.MachineDetail, error) {
	return r.loader.ConfigUsed(ctx, obj.Title)
}

// Config returns graph.ConfigResolver implementation.
func (r *Resolver) Config() graph.ConfigResolver { return &configResolver{r} }

type configResolver struct{ *Resolver }
