package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"context"
	"time"

	"github.com/web3tea/curio-dashboard/graph"
	"github.com/web3tea/curio-dashboard/graph/cachecontrol"
	"github.com/web3tea/curio-dashboard/graph/model"
)

// Provider is the resolver for the provider field.
func (r *iPNIAdvertisementResolver) Provider(ctx context.Context, obj *model.IPNIAdvertisement) (*model.IPNIPeerID, error) {
	return r.loader.IpniPeerID(ctx, nil, obj.ProviderPeerID)
}

// TotalAdvertisements is the resolver for the totalAdvertisements field.
func (r *iPNIStatsResolver) TotalAdvertisements(ctx context.Context, obj *model.IPNIStats) (int, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, time.Minute*5)
	return r.loader.IpniTotalAdvertisements(ctx)
}

// PreviousTotalAdvertisements is the resolver for the previousTotalAdvertisements field.
func (r *iPNIStatsResolver) PreviousTotalAdvertisements(ctx context.Context, obj *model.IPNIStats) (int, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, time.Minute*5)
	// todo: implement previous total advertisements
	// use the current advertisement count for now
	return r.loader.IpniTotalAdvertisements(ctx)
}

// Providers is the resolver for the providers field.
func (r *iPNIStatsResolver) Providers(ctx context.Context, obj *model.IPNIStats) (int, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, time.Minute*5)
	return r.loader.IpniTotalProviders(ctx)
}

// PreviousProviders is the resolver for the previousProviders field.
func (r *iPNIStatsResolver) PreviousProviders(ctx context.Context, obj *model.IPNIStats) (int, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, time.Minute*5)
	// todo: implement previous providers
	// use the current provider count for now
	return r.loader.IpniTotalProviders(ctx)
}

// Indexed is the resolver for the indexed field.
func (r *iPNIStatsResolver) Indexed(ctx context.Context, obj *model.IPNIStats) (int, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, time.Minute*5)
	return r.loader.IpniTotalIndexed(ctx)
}

// PreviousIndexed is the resolver for the previousIndexed field.
func (r *iPNIStatsResolver) PreviousIndexed(ctx context.Context, obj *model.IPNIStats) (int, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, time.Minute*5)
	// todo: implement previous indexed
	// use the current indexed count for now
	return r.loader.IpniTotalIndexed(ctx)
}

// Skipped is the resolver for the skipped field.
func (r *iPNIStatsResolver) Skipped(ctx context.Context, obj *model.IPNIStats) (int, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, time.Minute*5)
	return r.loader.IpniTotalSkipped(ctx)
}

// PreviousSkipped is the resolver for the previousSkipped field.
func (r *iPNIStatsResolver) PreviousSkipped(ctx context.Context, obj *model.IPNIStats) (int, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, time.Minute*5)
	// todo: implement previous skipped
	// use the current skipped count for now
	return r.loader.IpniTotalSkipped(ctx)
}

// PendingTasks is the resolver for the pendingTasks field.
func (r *iPNIStatsResolver) PendingTasks(ctx context.Context, obj *model.IPNIStats) (int, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, time.Minute*5)
	return r.loader.IpniPendingTasks(ctx)
}

// PreviousPendingTasks is the resolver for the previousPendingTasks field.
func (r *iPNIStatsResolver) PreviousPendingTasks(ctx context.Context, obj *model.IPNIStats) (int, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, time.Minute*5)
	// todo: implement previous pending tasks
	// use the current pending tasks count for now
	return r.loader.IpniPendingTasks(ctx)
}

// IpniStats is the resolver for the ipniStats field.
func (r *queryResolver) IpniStats(ctx context.Context) (*model.IPNIStats, error) {
	return &model.IPNIStats{}, nil
}

// IpniAdvertisement is the resolver for the ipniAdvertisement field.
func (r *queryResolver) IpniAdvertisement(ctx context.Context, orderNumber int) (*model.IPNIAdvertisement, error) {
	return r.loader.IpniAdvertisement(ctx, orderNumber)
}

// IpniAdvertisements is the resolver for the ipniAdvertisements field.
func (r *queryResolver) IpniAdvertisements(ctx context.Context, offset int, limit int, provider *string, isSkip *bool, isRemoved *bool) ([]*model.IPNIAdvertisement, error) {
	return r.loader.IpniAdvertisements(ctx, provider, isSkip, isRemoved, offset, limit)
}

// IpniAdvertisementsCount is the resolver for the ipniAdvertisementsCount field.
func (r *queryResolver) IpniAdvertisementsCount(ctx context.Context, provider *string, isSkip *bool, isRemoved *bool) (int, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, time.Minute*5)
	return r.loader.IpniAdvertisementsCount(ctx, provider, isSkip, isRemoved)
}

// IPNIAdvertisement returns graph.IPNIAdvertisementResolver implementation.
func (r *Resolver) IPNIAdvertisement() graph.IPNIAdvertisementResolver {
	return &iPNIAdvertisementResolver{r}
}

// IPNIStats returns graph.IPNIStatsResolver implementation.
func (r *Resolver) IPNIStats() graph.IPNIStatsResolver { return &iPNIStatsResolver{r} }

type (
	iPNIAdvertisementResolver struct{ *Resolver }
	iPNIStatsResolver         struct{ *Resolver }
)
