package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/strahe/curio-dashboard/graph"
	"github.com/strahe/curio-dashboard/graph/model"
	"github.com/strahe/curio-dashboard/types"
)

// Info is the resolver for the info field.
func (r *minerResolver) Info(ctx context.Context, obj *model.Miner) (*model.MinerInfo, error) {
	panic(fmt.Errorf("not implemented: Info - info"))
}

// Power is the resolver for the power field.
func (r *minerResolver) Power(ctx context.Context, obj *model.Miner) (*model.MinerPower, error) {
	panic(fmt.Errorf("not implemented: Power - power"))
}

// AvailableBalance is the resolver for the availableBalance field.
func (r *minerResolver) AvailableBalance(ctx context.Context, obj *model.Miner) (*types.BigInt, error) {
	panic(fmt.Errorf("not implemented: AvailableBalance - availableBalance"))
}

// Miner returns graph.MinerResolver implementation.
func (r *Resolver) Miner() graph.MinerResolver { return &minerResolver{r} }

type minerResolver struct{ *Resolver }
