package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/samber/lo"
	"github.com/web3tea/curio-dashboard/graph"
	"github.com/web3tea/curio-dashboard/graph/cachecontrol"
	"github.com/web3tea/curio-dashboard/graph/loaders"
	"github.com/web3tea/curio-dashboard/graph/model"
	"github.com/web3tea/curio-dashboard/types"
)

// RemoveSector is the resolver for the removeSector field.
func (r *mutationResolver) RemoveSector(ctx context.Context, miner types.Address, sectorNumber int) (bool, error) {
	if err := r.curioAPI.SectorRemove(ctx, int(lo.FromPtr(miner.ID())), sectorNumber); err != nil {
		return false, err
	}
	return true, nil
}

// RestartSector is the resolver for the restartSector field.
func (r *mutationResolver) RestartSector(ctx context.Context, miner types.Address, sectorNumber int) (bool, error) {
	if err := r.curioAPI.SectorResume(ctx, int64(lo.FromPtr(miner.ID())), int64(sectorNumber)); err != nil {
		return false, err
	}
	return true, nil
}

// RestartAllFailedSectors is the resolver for the restartAllFailedSectors field.
func (r *mutationResolver) RestartAllFailedSectors(ctx context.Context) (bool, error) {
	err := r.curioAPI.PipelinePorepRestartAll(ctx)
	if err != nil {
		return false, err
	}
	return true, err
}

// Sectors is the resolver for the sectors field.
func (r *queryResolver) Sectors(ctx context.Context, actor *types.Address, sectorNumber *int, offset int, limit int) ([]*model.Sector, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, sectorDefaultCacheAge)
	if actor != nil && sectorNumber != nil {
		meta, err := r.loader.SectorMeta(ctx, *actor, *sectorNumber)
		if err != nil {
			return nil, err
		}
		return []*model.Sector{{SpID: *actor, SectorNum: *sectorNumber, Meta: meta}}, nil
	}
	metas, err := r.loader.SectorMetas(ctx, actor, offset, limit)
	if err != nil {
		return nil, err
	}
	var out []*model.Sector
	for _, meta := range metas {
		out = append(out, &model.Sector{
			SpID:      meta.SpID,
			SectorNum: meta.SectorNum,
			Meta:      meta,
		})
	}
	return out, nil
}

// SectorsCount is the resolver for the sectorsCount field.
func (r *queryResolver) SectorsCount(ctx context.Context, actor *types.Address) (int, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, time.Minute*5)
	return r.loader.SectorsCount(ctx, actor)
}

// Sector is the resolver for the sector field.
func (r *queryResolver) Sector(ctx context.Context, actor types.Address, sectorNumber int) (*model.Sector, error) {
	return &model.Sector{SpID: actor, SectorNum: sectorNumber}, nil
}

// SectorSummary is the resolver for the sectorSummary field.
func (r *queryResolver) SectorSummary(ctx context.Context) (*model.SectorSummary, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, sectorDefaultCacheAge)
	return r.loader.SectorSummary(ctx)
}

// SnapSectors is the resolver for the snapSectors field.
func (r *queryResolver) SnapSectors(ctx context.Context, actor *types.Address, sectorNumber *int, offset int, limit int) ([]*model.SectorSnapPipeline, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, sectorDefaultCacheAge)
	if actor != nil && sectorNumber != nil {
		snap, err := r.loader.SnapPipeline(ctx, *actor, *sectorNumber)
		if err != nil {
			return nil, err
		}
		return []*model.SectorSnapPipeline{snap}, nil
	}
	return r.loader.SnapPipelines(ctx, actor, offset, limit)
}

// SnapSectorsCount is the resolver for the snapSectorsCount field.
func (r *queryResolver) SnapSectorsCount(ctx context.Context, actor *types.Address) (int, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, time.Minute*5)
	return r.loader.SnapSectorsCount(ctx, actor)
}

// SnapSummary is the resolver for the snapSummary field.
func (r *queryResolver) SnapSummary(ctx context.Context) (*model.SnapSummary, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, sectorDefaultCacheAge)
	return r.loader.SnapSummary(ctx)
}

// UnsealSectors is the resolver for the unsealSectors field.
func (r *queryResolver) UnsealSectors(ctx context.Context, actor *types.Address, sectorNumber *int, offset int, limit int) ([]*model.SectorUnsealPipeline, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, sectorDefaultCacheAge)
	if actor != nil && sectorNumber != nil {
		unseal, err := r.loader.UnsealPipeline(ctx, *actor, *sectorNumber)
		if err != nil {
			return nil, err
		}
		return []*model.SectorUnsealPipeline{unseal}, nil
	}
	return r.loader.UnsealPipelines(ctx, actor, offset, limit)
}

// UnsealSectorsCount is the resolver for the unsealSectorsCount field.
func (r *queryResolver) UnsealSectorsCount(ctx context.Context, actor *types.Address) (int, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, time.Minute*5)
	return r.loader.UnsealSectorsCount(ctx, actor)
}

// ID is the resolver for the id field.
func (r *sectorResolver) ID(ctx context.Context, obj *model.Sector) (string, error) {
	return fmt.Sprintf("%s:%d", obj.SpID, obj.SectorNum), nil
}

// Status is the resolver for the status field.
func (r *sectorResolver) Status(ctx context.Context, obj *model.Sector) (model.TaskStatus, error) {
	porep, err := r.loader.Porep(ctx, obj.SpID, obj.SectorNum)
	if err == nil {
		r := &porepResolver{r.Resolver}
		return r.Status(ctx, porep)
	}
	_, err = r.loader.SectorMeta(ctx, obj.SpID, obj.SectorNum)
	if err == nil {
		return model.TaskStatusCompleted, nil
	}
	return model.TaskStatusFailed, nil
}

// Meta is the resolver for the meta field.
func (r *sectorResolver) Meta(ctx context.Context, obj *model.Sector) (*model.SectorMeta, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, sectorDefaultCacheAge)
	if obj.Meta != nil {
		return obj.Meta, nil
	}
	m, err := r.loader.SectorMeta(ctx, obj.SpID, obj.SectorNum)
	if errors.Is(err, loaders.ErrorNotFound) {
		return nil, nil
	}
	return m, nil
}

// Porep is the resolver for the porep field.
func (r *sectorResolver) Porep(ctx context.Context, obj *model.Sector) (*model.Porep, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, sectorDefaultCacheAge)
	return r.loader.Porep(ctx, obj.SpID, obj.SectorNum)
}

// Locations is the resolver for the locations field.
func (r *sectorResolver) Locations(ctx context.Context, obj *model.Sector) ([]*model.SectorLocation, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, sectorDefaultCacheAge)
	return r.loader.SectorLocations(ctx, obj.SpID, obj.SectorNum)
}

// Pieces is the resolver for the pieces field.
func (r *sectorResolver) Pieces(ctx context.Context, obj *model.Sector) ([]*model.SectorMetaPiece, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, sectorDefaultCacheAge)
	return r.loader.SectorPieces(ctx, obj.SpID, obj.SectorNum)
}

// Tasks is the resolver for the tasks field.
func (r *sectorResolver) Tasks(ctx context.Context, obj *model.Sector) ([]*model.Task, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, sectorDefaultCacheAge)
	return r.loader.SectorTasks(ctx, obj.SpID, obj.SectorNum)
}

// Events is the resolver for the events field.
func (r *sectorResolver) Events(ctx context.Context, obj *model.Sector) ([]*model.TaskHistory, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, sectorDefaultCacheAge)
	return r.loader.SectorEvents(ctx, obj.SpID, obj.SectorNum)
}

// Storage is the resolver for the storage field.
func (r *sectorLocationResolver) Storage(ctx context.Context, obj *model.SectorLocation) (*model.Storage, error) {
	return &model.Storage{ID: obj.StorageID}, nil
}

// ID is the resolver for the id field.
func (r *sectorMetaResolver) ID(ctx context.Context, obj *model.SectorMeta) (string, error) {
	return fmt.Sprintf("%s-%d", obj.SpID, obj.SectorNum), nil
}

// Meta is the resolver for the meta field on SectorSnapPipeline.
func (r *sectorSnapPipelineResolver) Meta(ctx context.Context, obj *model.SectorSnapPipeline) (*model.SectorMeta, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, sectorDefaultCacheAge)
	return r.loader.SectorMeta(ctx, obj.SpID, obj.SectorNumber)
}

// Pieces is the resolver for the pieces field on SectorSnapPipeline.
func (r *sectorSnapPipelineResolver) Pieces(ctx context.Context, obj *model.SectorSnapPipeline) ([]*model.SectorSnapPiece, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, sectorDefaultCacheAge)
	return r.loader.SnapPieces(ctx, obj.SpID, obj.SectorNumber)
}

// Meta is the resolver for the meta field on SectorUnsealPipeline.
func (r *sectorUnsealPipelineResolver) Meta(ctx context.Context, obj *model.SectorUnsealPipeline) (*model.SectorMeta, error) {
	cachecontrol.SetHint(ctx, cachecontrol.ScopePrivate, sectorDefaultCacheAge)
	return r.loader.SectorMeta(ctx, obj.SpID, obj.SectorNumber)
}

// Sector returns graph.SectorResolver implementation.
func (r *Resolver) Sector() graph.SectorResolver { return &sectorResolver{r} }

// SectorLocation returns graph.SectorLocationResolver implementation.
func (r *Resolver) SectorLocation() graph.SectorLocationResolver { return &sectorLocationResolver{r} }

// SectorMeta returns graph.SectorMetaResolver implementation.
func (r *Resolver) SectorMeta() graph.SectorMetaResolver { return &sectorMetaResolver{r} }

// SectorSnapPipeline returns graph.SectorSnapPipelineResolver implementation.
func (r *Resolver) SectorSnapPipeline() graph.SectorSnapPipelineResolver {
	return &sectorSnapPipelineResolver{r}
}

// SectorUnsealPipeline returns graph.SectorUnsealPipelineResolver implementation.
func (r *Resolver) SectorUnsealPipeline() graph.SectorUnsealPipelineResolver {
	return &sectorUnsealPipelineResolver{r}
}

type sectorResolver struct{ *Resolver }
type sectorLocationResolver struct{ *Resolver }
type sectorMetaResolver struct{ *Resolver }
type sectorSnapPipelineResolver struct{ *Resolver }
type sectorUnsealPipelineResolver struct{ *Resolver }
