package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"

	"github.com/strahe/curio-dashboard/graph"
	"github.com/strahe/curio-dashboard/graph/model"
)

// ID is the resolver for the id field.
func (r *storagePathResolver) ID(ctx context.Context, obj *model.StoragePath) (string, error) {
	return obj.StorageID, nil
}

// Type is the resolver for the type field.
func (r *storagePathResolver) Type(ctx context.Context, obj *model.StoragePath) (model.StorageType, error) {
	switch {
	case obj.CanStore && obj.CanSeal:
		return model.StorageTypeHybrid, nil
	case obj.CanSeal:
		return model.StorageTypeSeal, nil
	case obj.CanStore:
		return model.StorageTypeStore, nil
	default:
		return model.StorageTypeReadonly, nil
	}
}

// StoragePath returns graph.StoragePathResolver implementation.
func (r *Resolver) StoragePath() graph.StoragePathResolver { return &storagePathResolver{r} }

type storagePathResolver struct{ *Resolver }
