import {
  mdiAlertOutline,
  mdiBlockHelper,
  mdiCheckboxMarkedCircleOutline,
  mdiChevronDown,
  mdiChevronUp,
  mdiCircleOutline,
  mdiCloseCircle,
  mdiEmoticonHappy,
  mdiEmoticonHappyOutline,
  mdiHeart,
  mdiHeartHalf,
  mdiHeartOutline,
  mdiHelpCircleOutline,
  mdiMagnify,
  mdiMenuDown,
  mdiReply,
} from '@mdi/js'

export const icons = {
  checkboxMarkedCircleOutline: mdiCheckboxMarkedCircleOutline,
  magnify: mdiMagnify,
  menuDown: mdiMenuDown,
  chevronUp: mdiChevronUp,
  chevronDown: mdiChevronDown,
  reply: mdiReply,
  circleOutline: mdiCircleOutline,
  blockHelper: mdiBlockHelper,
  closeCircle: mdiCloseCircle,
  alertOutline: mdiAlertOutline,
  helpCircleOutline: mdiHelpCircleOutline,
  emoticonHappy: mdiEmoticonHappy,
  emoticonHappyOutline: mdiEmoticonHappyOutline,
  heart: mdiHeart,
  heartOutline: mdiHeartOutline,
  heartHalf: mdiHeartHalf,
}
